name: Code Quality Check

on:
  push:
    branches:
      - dev

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: pip install flake8
      
      - name: Run flake8
        run: flake8
